site_name: DocOps Portfolio
site_url: https://pasichnyk234.github.io/docops-portfolio/

nav:
  - Home: index.md
  - How-To: how-to.md
  - Reference: reference.md
  - Troubleshooting: troubleshooting.md
  - Projects: projects.md
  - Ã–koProjekt: oekoprofit.md
  - Confluence-Projektvorlage: reference/confluence-project-template.md

