site_name: DocOps Portfolio
nav:
  - Home: index.md
  - How-To: how-to.md
  - Reference: reference.md
  - Troubleshooting: troubleshooting.md
  - Projects: projects.md
  - Ökoprojekt: ökoprofit.md
  - Reference:
    - Confluence-Projektvorlage: reference/confluence-projektvorlage.md
